name: Donation-Store-BungeeCord
author: Donation Store
version: 2.1
main: net.donationstore.bungeecord.DonationStorePlugin
website: https://donationstore.net
commands:
  ds:
    description: Main command for the Donation Store plugin.
    usage: /ds